---
title: Life Work Integration
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: true
  uploads:
    title: Uploads
    output: true
    path: assets/img
defaults:
- scope:
    path: assets/img
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
