---
title: Life Work Integration
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  slide1:
    title: Section1
    output: false
  sections:
    title: Sections
    output: true
  uploads:
    title: Uploads
    output: true
    path: assets/img
defaults:
- scope:
    path: assets/img
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: assets/img
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: slides
  values:
    Slide Image: 
    Headline: Lifeworkintegration
    Slide txt: 
permalink: pretty
Email: jamie@lifeworkintegration.com
Phone: 424-442-9219
