---
title: Life Work Integration
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  section1:
    title: Section1
    output: false
  section2:
    title: Section2
    output: true
  section3:
    title: Section3
    output: true
  section4:
    title: Section4
    output: true
  section5:
    title: Section5
    output: true
  section6:
    title: Section6
    output: true
  section7:
    title: Section7
    output: true
  section8:
    title: Section8
    output: true
  section9:
    title: Section9
    output: true
  sections:
    title: Sections
    output: true
  uploads:
    title: Uploads
    output: true
    path: assets/img
defaults:
- scope:
    path: assets/img
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: assets/img
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: section1
  values:
    Slide Image: 
    Headline: Lifeworkintegration
    Slide txt: 
permalink: pretty
Email: jamie@lifeworkintegration.com
Phone: 424-442-9219
Twitter: http://twitter.com/jdouraghy
Facebook: https://www.facebook.com/lifeworkintegration
Instagram: https://www.instagram.com/jdouraghy/
LinkedIn: https://www.linkedin.com/in/jdouraghy
Copyright: "&copy; 2014-2019 Jamie Douraghy"
